version: "3"

networks:
  transcendence:
    driver: bridge

volumes:
  db-volume:

services:
  postgres:
    container_name: postgres
    image: postgres:15.2-alpine3.17
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - transcendence
    volumes:
      - db-volume:/var/lib/postgresql/data
    restart: always
  web:
    container_name: web
    build:
      context: requirements/web/
      dockerfile: Dockerfile
    environment:
      HOST_NAME: ${HOST_NAME}
      OAUTH_42_CLIENT_ID: ${OAUTH_42_CLIENT_ID}
      OAUTH_42_CLIENT_SECRET: ${OAUTH_42_CLIENT_SECRET}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - postgres
    networks:
      - transcendence
    restart: always
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx/
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - transcendence
    restart: always
